#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 10, 2019 02:35:06 PM +07  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m85" -background #645cf8 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 797x732+607+188
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "MainGame" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent70 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify left 
    vTcl:DefineAlias "$top.ent70" "Entry1" vTcl:WidgetProc "MainGame" 1
    button $top.but72 \
        -activebackground #ff6666 -activeforeground #ffffff \
        -background #ff0000 -disabledforeground #a3a3a3 \
        -font {-family {UD Digi Kyokasho NP-R} -size 14} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text EXIT 
    vTcl:DefineAlias "$top.but72" "BtnExitMenu" vTcl:WidgetProc "MainGame" 1
    label $top.lab73 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {UD Digi Kyokasho NP-R} -size 14} -foreground #ffffff \
        -text {Nama Turn} 
    vTcl:DefineAlias "$top.lab73" "LblTurn" vTcl:WidgetProc "MainGame" 1
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but75" "Button0_0" vTcl:WidgetProc "MainGame" 1
    button $top.but77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but77" "Button0_1" vTcl:WidgetProc "MainGame" 1
    button $top.but78 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but78" "Button0_2" vTcl:WidgetProc "MainGame" 1
    button $top.but79 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but79" "Button1_0" vTcl:WidgetProc "MainGame" 1
    button $top.but80 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but80" "Button2_0" vTcl:WidgetProc "MainGame" 1
    button $top.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but81" "Button1_1" vTcl:WidgetProc "MainGame" 1
    button $top.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but82" "Button1_2" vTcl:WidgetProc "MainGame" 1
    button $top.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but83" "Button2_1" vTcl:WidgetProc "MainGame" 1
    button $top.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but84" "Button2_2" vTcl:WidgetProc "MainGame" 1
    set site_3_0 $top.m85
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent70 \
        -in $top -x 170 -y 560 -width 450 -relwidth 0 -height 120 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but72 \
        -in $top -x 670 -y 640 -width 100 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 170 -y 30 -width 450 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 170 -y 90 -width 150 -relwidth 0 -height 150 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 320 -y 90 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but78 \
        -in $top -x 470 -y 90 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but79 \
        -in $top -x 170 -y 230 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but80 \
        -in $top -x 170 -y 370 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but81 \
        -in $top -x 320 -y 230 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but82 \
        -in $top -x 470 -y 230 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but83 \
        -in $top -x 320 -y 370 -width 150 -height 150 -anchor nw \
        -bordermode ignore 
    place $top.but84 \
        -in $top -x 470 -y 370 -width 150 -height 150 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

