#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 10, 2019 05:33:18 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainGame (root)
    unknown_support.init(root, top)
    root.mainloop()

w = None
def create_MainGame(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = MainGame (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainGame():
    global w
    w.destroy()
    w = None

class MainGame:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font12 = "-family {Segoe UI} -size 72 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("797x732+607+188")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("New Toplevel")
        top.configure(background="#645cf8")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.213, rely=0.765,height=120, relwidth=0.565)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.BtnExitMenu = tk.Button(top)
        self.BtnExitMenu.place(relx=0.841, rely=0.874, height=50, width=100)
        self.BtnExitMenu.configure(activebackground="#ff6666")
        self.BtnExitMenu.configure(activeforeground="#ffffff")
        self.BtnExitMenu.configure(background="#ff0000")
        self.BtnExitMenu.configure(disabledforeground="#a3a3a3")
        self.BtnExitMenu.configure(font="-family {UD Digi Kyokasho NP-R} -size 14")
        self.BtnExitMenu.configure(foreground="#ffffff")
        self.BtnExitMenu.configure(highlightbackground="#d9d9d9")
        self.BtnExitMenu.configure(highlightcolor="black")
        self.BtnExitMenu.configure(pady="0")
        self.BtnExitMenu.configure(text='''EXIT''')

        self.LblTurn_3 = tk.Label(top)
        self.LblTurn_3.place(relx=0.376, rely=0.041, height=40, width=190)
        self.LblTurn_3.configure(activebackground="#f9f9f9")
        self.LblTurn_3.configure(activeforeground="black")
        self.LblTurn_3.configure(background="#000000")
        self.LblTurn_3.configure(disabledforeground="#a3a3a3")
        self.LblTurn_3.configure(font="-family {UD Digi Kyokasho NP-R} -size 14")
        self.LblTurn_3.configure(foreground="#ffffff")
        self.LblTurn_3.configure(highlightbackground="#d9d9d9")
        self.LblTurn_3.configure(highlightcolor="black")
        self.LblTurn_3.configure(text='''Nama Turn''')

        self.Button0_0 = tk.Button(top)
        self.Button0_0.place(relx=0.213, rely=0.123, height=150, width=150)
        self.Button0_0.configure(activebackground="#ececec")
        self.Button0_0.configure(activeforeground="#000000")
        self.Button0_0.configure(background="#000000")
        self.Button0_0.configure(disabledforeground="#a3a3a3")
        self.Button0_0.configure(font=font12)
        self.Button0_0.configure(foreground="#ffffff")
        self.Button0_0.configure(highlightbackground="#d9d9d9")
        self.Button0_0.configure(highlightcolor="black")
        self.Button0_0.configure(pady="0")
        self.Button0_0.configure(text='''X''')

        self.Button0_1 = tk.Button(top)
        self.Button0_1.place(relx=0.402, rely=0.123, height=150, width=150)
        self.Button0_1.configure(activebackground="#ececec")
        self.Button0_1.configure(activeforeground="#000000")
        self.Button0_1.configure(background="#000000")
        self.Button0_1.configure(disabledforeground="#a3a3a3")
        self.Button0_1.configure(font=font12)
        self.Button0_1.configure(foreground="#ffffff")
        self.Button0_1.configure(highlightbackground="#d9d9d9")
        self.Button0_1.configure(highlightcolor="black")
        self.Button0_1.configure(pady="0")
        self.Button0_1.configure(text='''O''')

        self.Button0_2 = tk.Button(top)
        self.Button0_2.place(relx=0.59, rely=0.123, height=150, width=150)
        self.Button0_2.configure(activebackground="#ececec")
        self.Button0_2.configure(activeforeground="#000000")
        self.Button0_2.configure(background="#000000")
        self.Button0_2.configure(disabledforeground="#a3a3a3")
        self.Button0_2.configure(font=font12)
        self.Button0_2.configure(foreground="#f9f9f9")
        self.Button0_2.configure(highlightbackground="#d9d9d9")
        self.Button0_2.configure(highlightcolor="black")
        self.Button0_2.configure(pady="0")
        self.Button0_2.configure(text='''X''')

        self.Button1_0 = tk.Button(top)
        self.Button1_0.place(relx=0.213, rely=0.314, height=150, width=150)
        self.Button1_0.configure(activebackground="#ececec")
        self.Button1_0.configure(activeforeground="#000000")
        self.Button1_0.configure(background="#000000")
        self.Button1_0.configure(disabledforeground="#a3a3a3")
        self.Button1_0.configure(font=font12)
        self.Button1_0.configure(foreground="#ffffff")
        self.Button1_0.configure(highlightbackground="#d9d9d9")
        self.Button1_0.configure(highlightcolor="black")
        self.Button1_0.configure(pady="0")
        self.Button1_0.configure(text='''O''')

        self.Button2_0 = tk.Button(top)
        self.Button2_0.place(relx=0.213, rely=0.505, height=150, width=150)
        self.Button2_0.configure(activebackground="#ececec")
        self.Button2_0.configure(activeforeground="#000000")
        self.Button2_0.configure(background="#000000")
        self.Button2_0.configure(disabledforeground="#a3a3a3")
        self.Button2_0.configure(font=font12)
        self.Button2_0.configure(foreground="#ffffff")
        self.Button2_0.configure(highlightbackground="#d9d9d9")
        self.Button2_0.configure(highlightcolor="black")
        self.Button2_0.configure(pady="0")
        self.Button2_0.configure(text='''O''')

        self.Button1_1 = tk.Button(top)
        self.Button1_1.place(relx=0.402, rely=0.314, height=150, width=150)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#000000")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font12)
        self.Button1_1.configure(foreground="#ffffff")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''X''')

        self.Button1_2 = tk.Button(top)
        self.Button1_2.place(relx=0.59, rely=0.314, height=150, width=150)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#000000")
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font=font12)
        self.Button1_2.configure(foreground="#ffffff")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''O''')

        self.Button2_1 = tk.Button(top)
        self.Button2_1.place(relx=0.402, rely=0.505, height=150, width=150)
        self.Button2_1.configure(activebackground="#ececec")
        self.Button2_1.configure(activeforeground="#000000")
        self.Button2_1.configure(background="#000000")
        self.Button2_1.configure(disabledforeground="#a3a3a3")
        self.Button2_1.configure(font=font12)
        self.Button2_1.configure(foreground="#ffffff")
        self.Button2_1.configure(highlightbackground="#d9d9d9")
        self.Button2_1.configure(highlightcolor="black")
        self.Button2_1.configure(pady="0")
        self.Button2_1.configure(text='''X''')

        self.Button2_2 = tk.Button(top)
        self.Button2_2.place(relx=0.59, rely=0.505, height=150, width=150)
        self.Button2_2.configure(activebackground="#ececec")
        self.Button2_2.configure(activeforeground="#000000")
        self.Button2_2.configure(background="#000000")
        self.Button2_2.configure(disabledforeground="#a3a3a3")
        self.Button2_2.configure(font=font12)
        self.Button2_2.configure(foreground="#ffffff")
        self.Button2_2.configure(highlightbackground="#d9d9d9")
        self.Button2_2.configure(highlightcolor="black")
        self.Button2_2.configure(pady="0")
        self.Button2_2.configure(text='''O''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.LblTurn_1 = tk.Label(top)
        self.LblTurn_1.place(relx=0.113, rely=0.041, height=40, width=190)
        self.LblTurn_1.configure(activebackground="#f9f9f9")
        self.LblTurn_1.configure(activeforeground="black")
        self.LblTurn_1.configure(background="#000000")
        self.LblTurn_1.configure(disabledforeground="#a3a3a3")
        self.LblTurn_1.configure(font="-family {UD Digi Kyokasho NP-R} -size 14")
        self.LblTurn_1.configure(foreground="#ffffff")
        self.LblTurn_1.configure(highlightbackground="#d9d9d9")
        self.LblTurn_1.configure(highlightcolor="black")
        self.LblTurn_1.configure(text='''Nama Turn''')

        self.LblTurn_2 = tk.Label(top)
        self.LblTurn_2.place(relx=0.64, rely=0.041, height=40, width=190)
        self.LblTurn_2.configure(activebackground="#f9f9f9")
        self.LblTurn_2.configure(activeforeground="black")
        self.LblTurn_2.configure(background="#000000")
        self.LblTurn_2.configure(disabledforeground="#a3a3a3")
        self.LblTurn_2.configure(font="-family {UD Digi Kyokasho NP-R} -size 14")
        self.LblTurn_2.configure(foreground="#ffffff")
        self.LblTurn_2.configure(highlightbackground="#d9d9d9")
        self.LblTurn_2.configure(highlightcolor="black")
        self.LblTurn_2.configure(text='''Nama Turn''')

        self.BtnExitMenu_3 = tk.Button(top)
        self.BtnExitMenu_3.place(relx=0.841, rely=0.765, height=50, width=100)
        self.BtnExitMenu_3.configure(activebackground="#ff6666")
        self.BtnExitMenu_3.configure(activeforeground="#ffffff")
        self.BtnExitMenu_3.configure(background="#45dd04")
        self.BtnExitMenu_3.configure(disabledforeground="#a3a3a3")
        self.BtnExitMenu_3.configure(font="-family {UD Digi Kyokasho NP-R} -size 14")
        self.BtnExitMenu_3.configure(foreground="#ffffff")
        self.BtnExitMenu_3.configure(highlightbackground="#d9d9d9")
        self.BtnExitMenu_3.configure(highlightcolor="black")
        self.BtnExitMenu_3.configure(pady="0")
        self.BtnExitMenu_3.configure(text='''START''')

if __name__ == '__main__':
    vp_start_gui()





