#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 10, 2019 01:59:52 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    unknown_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {UD Digi Kyokasho NP-R} -size 28 -weight "  \
            "normal -slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("797x712+607+188")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("Tic Tac Toe")
        top.configure(background="#645cf8")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.EntryNama = tk.Entry(top)
        self.EntryNama.place(relx=0.326, rely=0.267,height=40, relwidth=0.314)
        self.EntryNama.configure(background="white")
        self.EntryNama.configure(disabledforeground="#a3a3a3")
        self.EntryNama.configure(font="TkFixedFont")
        self.EntryNama.configure(foreground="#000000")
        self.EntryNama.configure(insertbackground="black")

        self.EntryAddr = tk.Entry(top)
        self.EntryAddr.place(relx=0.326, rely=0.435,height=40, relwidth=0.314)
        self.EntryAddr.configure(background="white")
        self.EntryAddr.configure(disabledforeground="#a3a3a3")
        self.EntryAddr.configure(font="TkFixedFont")
        self.EntryAddr.configure(foreground="#000000")
        self.EntryAddr.configure(highlightbackground="#d9d9d9")
        self.EntryAddr.configure(highlightcolor="black")
        self.EntryAddr.configure(insertbackground="black")
        self.EntryAddr.configure(selectbackground="#c4c4c4")
        self.EntryAddr.configure(selectforeground="black")

        self.LblNama = tk.Label(top)
        self.LblNama.place(relx=0.326, rely=0.211, height=40, width=250)
        self.LblNama.configure(background="#645cf8")
        self.LblNama.configure(disabledforeground="#a3a3a3")
        self.LblNama.configure(font=font9)
        self.LblNama.configure(foreground="#000000")
        self.LblNama.configure(text='''Nama''')

        self.LblAddress = tk.Label(top)
        self.LblAddress.place(relx=0.326, rely=0.379, height=40, width=250)
        self.LblAddress.configure(activebackground="#f9f9f9")
        self.LblAddress.configure(activeforeground="black")
        self.LblAddress.configure(background="#645cf8")
        self.LblAddress.configure(disabledforeground="#a3a3a3")
        self.LblAddress.configure(font="-family {Segoe UI} -size 20")
        self.LblAddress.configure(foreground="#000000")
        self.LblAddress.configure(highlightbackground="#d9d9d9")
        self.LblAddress.configure(highlightcolor="black")
        self.LblAddress.configure(text='''Host Name''')

        self.BtnGo = tk.Button(top)
        self.BtnGo.place(relx=0.389, rely=0.632, height=80, width=150)
        self.BtnGo.configure(activebackground="#51ff51")
        self.BtnGo.configure(activeforeground="#ffffff")
        self.BtnGo.configure(background="#00ff00")
        self.BtnGo.configure(borderwidth="0")
        self.BtnGo.configure(disabledforeground="#a3a3a3")
        self.BtnGo.configure(font=font10)
        self.BtnGo.configure(foreground="#ffffff")
        self.BtnGo.configure(highlightbackground="#d9d9d9")
        self.BtnGo.configure(highlightcolor="black")
        self.BtnGo.configure(pady="0")
        self.BtnGo.configure(text='''GO!''')

if __name__ == '__main__':
    vp_start_gui()





