#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 10, 2019 11:28:48 AM +07  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background #645cf8 
    wm focusmodel $top passive
    wm geometry $top 797x652+607+188
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but46 \
        -activebackground #51ff51 -activeforeground #ffffff \
        -background #00ff00 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {UD Digi Kyokasho NP-R} -size 24 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text START 
    vTcl:DefineAlias "$top.but46" "BtnStart" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground #ff6666 -activeforeground #ffffff \
        -background #ff0000 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {UD Digi Kyokasho NP-R} -size 24 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text EXIT 
    vTcl:DefineAlias "$top.but47" "BtnExit" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -background #645cf8 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 48} -foreground $vTcl(actual_gui_fg) \
        -text {Tic Tac Toe} 
    vTcl:DefineAlias "$top.lab51" "TitleLabel" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 210 -y 450 -width 160 -relwidth 0 -height 80 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 400 -y 450 -width 160 -relwidth 0 -height 80 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 200 -y 60 -width 384 -relwidth 0 -height 161 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

